export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_PRODTUCT_LIST_REQUEST = "GET_PRODTUCT_LIST_REQUEST";
export const GET_PRODTUCT_LIST_SUCCESS = "GET_PRODTUCT_LIST_SUCCESS";
export const GET_PRODTUCT_LIST_FAILURE = "GET_PRODTUCT_LIST_FAILURE";
