export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_PRODTUCT_LIST_REQUEST = "GET_PRODTUCT_LIST_REQUEST";
export const GET_PRODTUCT_LIST_SUCCESS = "GET_PRODTUCT_LIST_SUCCESS";
export const GET_PRODTUCT_LIST_FAILURE = "GET_PRODTUCT_LIST_FAILURE";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const ADD_TO_FAV_REQUEST = "ADD_TO_FAV_REQUEST";
export const ADD_TO_FAV_SUCCESS = "ADD_TO_FAV_SUCCESS";
export const ADD_TO_FAV_FAILURE = "ADD_TO_FAV_FAILURE";

export const REMOVE_FROM_FAV_REQUEST = "REMOVE_FROM_FAV_REQUEST";
export const REMOVE_FROM_FAV_SUCCESS = "REMOVE_FROM_FAV_SUCCESS";
export const REMOVE_FROM_FAV_FAILURE = "REMOVE_FROM_FAV_FAILURE";
