export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_PRODTUCT_LIST_REQUEST = "GET_PRODTUCT_LIST_REQUEST";
export const GET_PRODTUCT_LIST_SUCCESS = "GET_PRODTUCT_LIST_SUCCESS";
export const GET_PRODTUCT_LIST_FAILURE = "GET_PRODTUCT_LIST_FAILURE";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
